name: CI

on:
  push:
    branches: [ main, implement-core ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        build_type: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup CMake
        uses: lukka/get-cmake@v3.21.2

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Configure with CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=$([[ "${{ matrix.compiler }}" == "gcc" ]] && echo g++ || echo clang++) \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                ..

      - name: Build
        run: |
          cd build
          cmake --build . -- -j$(nproc)

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
